name: Reusable Workflow

on:
  workflow_call:
    inputs:
      input1:
        description: "Description for input1"
        required: true
        type: string
      input2:
        description: "Description for input2"
        required: false
        default: "default value for input2"
        type: string

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Print inputs
        run: |
          echo "Input1: ${{ inputs.input1 }}"
          echo "Input2: ${{ inputs.input2 }}"
