name: Reusable Workflow

on:
  workflow_call:
    inputs:
      input1:
        description: "Description for input1"
        required: true
        type: string
      input2:
        description: "Description for input2"
        required: false
        default: "default value for input2"
        type: string

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Save inputs to environment variables
        run: |
          echo "INPUT1=${{ inputs.input1 }}" >> $GITHUB_ENV
          echo "INPUT2=${{ inputs.input2 }}" >> $GITHUB_ENV

      - name: Print inputs
        run: |
          echo "Input1: $INPUT1"
          echo "Input2: $INPUT2"
          echo "Input1: from GITHUB_ENV ${{ env.Input1 }}"
          echo "Input2: from GITHUB_ENV ${{ env.Input2 }}"
